openapi: 3.1.0
x-stoplight:
  id: rqr3959thgmh3
info:
  title: Papuaa
  version: '1.0'
  summary: API principal del proyecto Papuaa
  contact:
    name: David
    email: david@papuaa.com
servers:
  - url: 'http://localhost:3000'
    description: LOCAL
paths:
  /session/login:
    post:
      summary: ''
      operationId: post-session-login
      responses:
        '200':
          description: OK
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Returns the cookie
      description: Login into the app
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
  /session/admin/register:
    post:
      summary: ''
      operationId: post-session-admin-register
      responses:
        '200':
          description: OK
          headers: {}
      description: Registers an admin user into the app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
components:
  schemas:
    User:
      title: User
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        _id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
          example: '1997-10-31'
        status:
          type: integer
          description: Set to true if the user's email has been verified.
        profileId:
          type: integer
          format: date
          description: The date that the user was created.
      required:
        - _id
        - name
        - surname
        - email
        - status
        - profileId
    HotelGroup:
      title: HotelGroup
      x-stoplight:
        id: g81slfj3ckoj4
      type: object
      properties:
        _id:
          type: integer
        name:
          type: string
        description:
          type: string
        billingId:
          type: integer
        status:
          type: string
    Model:
      title: Model
      x-stoplight:
        id: rveapmjsjk3w1
      type: object
      properties:
        _id:
          type: integer
  securitySchemes:
    API Token:
      type: http
      scheme: bearer
x-internal: false
